CREATE TABLE IF NOT EXISTS "Usuarios" (
	"usuario_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"first_name" VARCHAR(50) NOT NULL,
	"middle_name" VARCHAR(50),
	"last_name" VARCHAR(100) NOT NULL,
	"credentials_id" BIGINT NOT NULL,
	PRIMARY KEY("usuario_id")
);




CREATE TABLE IF NOT EXISTS "Credenciales" (
	"credentials_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(25) NOT NULL UNIQUE,
	"password" VARCHAR(28) NOT NULL,
	PRIMARY KEY("credentials_id")
);




CREATE TABLE IF NOT EXISTS "Denuncias" (
	"report_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"description" TEXT NOT NULL,
	"event_timestamp" TIMESTAMP NOT NULL,
	"city_province" TEXT NOT NULL,
	"is_private" BOOLEAN NOT NULL,
	"report_type" VARCHAR(20) NOT NULL,
	"usuario_id" BIGINT NOT NULL,
	PRIMARY KEY("report_id")
);



ALTER TABLE "Usuarios"
ADD FOREIGN KEY("credentials_id") REFERENCES "Credenciales"("credentials_id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "Denuncias"
ADD FOREIGN KEY("usuario_id") REFERENCES "Usuarios"("usuario_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;